"""A versão de Python e Node é a MESMA em todo lugar que a fixa.

Existe para tornar seguro aceitar bump de imagem base — e o motivo é um PR
concreto. O Dependabot abriu o #54 (`python:3.12-slim` -> `3.14-slim`) mexendo
só no `backend/Dockerfile`. Aquele PR passaria em TODOS os checks: o CI instala
o Python do `setup-python`, que continuava em 3.12, e a suíte roda nele. O que
iria para produção era outra coisa — uma imagem 3.14 rodando um
`requirements.txt` resolvido para 3.12, com markers e backports do Python
errado.

A saída não é proibir o bump, é fazer o PR incompleto FALHAR dizendo o que
falta. Com este gate, o #54 fica vermelho apontando `ci.yml` e o compilado; com
os três subindo juntos, o CI de verdade testa o Python novo e o merge é seguro.

Mesma ideia para o Node entre `ci.yml` e o `frontend/Dockerfile`.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CI = ROOT / ".github" / "workflows" / "ci.yml"
DOCKERFILE_BACKEND = ROOT / "backend" / "Dockerfile"
DOCKERFILE_FRONTEND = ROOT / "frontend" / "Dockerfile"
RELOCK = ROOT / "scripts" / "relock.sh"
COMPILADO = ROOT / "backend" / "requirements.txt"


def _do_ci(chave: str) -> str:
    achado = re.search(rf"^  {chave}: '([^']+)'", CI.read_text(encoding="utf-8"), re.M)
    assert achado, f"{chave} sumiu do bloco env: do ci.yml — era a fonte única"
    return achado.group(1)


def test_python_e_o_mesmo_no_ci_no_dockerfile_e_no_compilado():
    do_ci = _do_ci("PYTHON_VERSION")

    imagem = re.search(r"^FROM python:([0-9.]+)-slim", DOCKERFILE_BACKEND.read_text(encoding="utf-8"), re.M)
    assert imagem, "não achei o FROM python: no backend/Dockerfile"

    # O compilado grava o Python que o resolveu. É o elo que mais dói quando
    # destoa: markers e backports condicionais mudam entre versões, e o sintoma
    # aparece só em produção.
    cabecalho = re.search(r"autogenerated by pip-compile with Python ([0-9.]+)", COMPILADO.read_text(encoding="utf-8"))
    assert cabecalho, "o requirements.txt compilado perdeu o cabeçalho do pip-compile"

    assert do_ci == imagem.group(1) == cabecalho.group(1), (
        "a versão do Python se descolou entre os três lugares que a fixam:\n"
        f"  .github/workflows/ci.yml (env.PYTHON_VERSION): {do_ci}\n"
        f"  backend/Dockerfile (FROM python:):             {imagem.group(1)}\n"
        f"  backend/requirements.txt (cabeçalho):          {cabecalho.group(1)}\n\n"
        "Para subir de versão, mude o Dockerfile e o ci.yml juntos e rode "
        "`scripts/relock.sh` (que lê a versão do Dockerfile). Subir só um deles "
        "entrega em produção uma imagem cujo compilado foi resolvido noutro Python."
    )


def test_node_e_o_mesmo_no_ci_e_no_dockerfile():
    do_ci = _do_ci("NODE_VERSION")

    imagem = re.search(r"^FROM node:([0-9.]+)-alpine", DOCKERFILE_FRONTEND.read_text(encoding="utf-8"), re.M)
    assert imagem, "não achei o FROM node: no frontend/Dockerfile"

    assert do_ci == imagem.group(1), (
        "a versão do Node se descolou:\n"
        f"  .github/workflows/ci.yml (env.NODE_VERSION): {do_ci}\n"
        f"  frontend/Dockerfile (FROM node:):            {imagem.group(1)}\n\n"
        "O build do frontend roda nos dois; versões diferentes significam que o "
        "bundle testado não é o bundle publicado."
    )


def test_relock_nao_tem_versao_de_python_escrita_na_mao():
    """O script tem que LER a versão, não repeti-la.

    Enquanto ele trazia `python:3.12` literal, era um quarto lugar para
    esquecer — e o mais silencioso, porque só se manifesta na próxima vez que
    alguém regenera o compilado.
    """
    texto = RELOCK.read_text(encoding="utf-8")
    codigo = "\n".join(
        linha for linha in texto.splitlines() if not linha.lstrip().startswith("#")
    )

    assert not re.search(r"python:[0-9]", codigo), (
        "scripts/relock.sh voltou a fixar a versão do Python direto no comando "
        "docker; ela deve sair do backend/Dockerfile"
    )
    assert "backend/Dockerfile" in codigo, (
        "scripts/relock.sh não lê mais a versão do backend/Dockerfile"
    )
