"""A versão de Python e Node é a MESMA em todo lugar que a fixa.

Existe para tornar seguro aceitar bump de imagem base — e o motivo é um PR
concreto. O Dependabot abriu o #54 (`python:3.12-slim` -> `3.14-slim`) mexendo
só no `backend/Dockerfile`. Aquele PR passaria em TODOS os checks: o CI instala
o Python do `setup-python`, que continuava em 3.12, e a suíte roda nele. O que
iria para produção era outra coisa — uma imagem 3.14 rodando um
`requirements.txt` resolvido para 3.12, com markers e backports do Python
errado.

A saída não é proibir o bump, é fazer o PR incompleto FALHAR dizendo o que
falta. Com este gate, o #54 fica vermelho apontando `ci.yml` e o compilado; com
os três subindo juntos, o CI de verdade testa o Python novo e o merge é seguro.

Mesma ideia para o Node entre `ci.yml` e o `frontend/Dockerfile`.
"""

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CI = ROOT / ".github" / "workflows" / "ci.yml"
DOCKERFILE_BACKEND = ROOT / "backend" / "Dockerfile"
DOCKERFILE_FRONTEND = ROOT / "frontend" / "Dockerfile"
RELOCK = ROOT / "scripts" / "relock.sh"
COMPILADO = ROOT / "backend" / "requirements.txt"
REQ_DEV = ROOT / "backend" / "requirements-dev.txt"
PRE_COMMIT = ROOT / ".pre-commit-config.yaml"


def _do_ci(chave: str) -> str:
    achado = re.search(rf"^  {chave}: '([^']+)'", CI.read_text(encoding="utf-8"), re.M)
    assert achado, f"{chave} sumiu do bloco env: do ci.yml — era a fonte única"
    return achado.group(1)


def test_python_e_o_mesmo_no_ci_no_dockerfile_e_no_compilado():
    do_ci = _do_ci("PYTHON_VERSION")

    imagem = re.search(r"^FROM python:([0-9.]+)-slim", DOCKERFILE_BACKEND.read_text(encoding="utf-8"), re.M)
    assert imagem, "não achei o FROM python: no backend/Dockerfile"

    # O compilado grava o Python que o resolveu. É o elo que mais dói quando
    # destoa: markers e backports condicionais mudam entre versões, e o sintoma
    # aparece só em produção.
    cabecalho = re.search(r"autogenerated by pip-compile with Python ([0-9.]+)", COMPILADO.read_text(encoding="utf-8"))
    assert cabecalho, "o requirements.txt compilado perdeu o cabeçalho do pip-compile"

    assert do_ci == imagem.group(1) == cabecalho.group(1), (
        "a versão do Python se descolou entre os três lugares que a fixam:\n"
        f"  .github/workflows/ci.yml (env.PYTHON_VERSION): {do_ci}\n"
        f"  backend/Dockerfile (FROM python:):             {imagem.group(1)}\n"
        f"  backend/requirements.txt (cabeçalho):          {cabecalho.group(1)}\n\n"
        "Para subir de versão, mude o Dockerfile e o ci.yml juntos e rode "
        "`scripts/relock.sh` (que lê a versão do Dockerfile). Subir só um deles "
        "entrega em produção uma imagem cujo compilado foi resolvido noutro Python."
    )


def test_node_e_o_mesmo_no_ci_e_no_dockerfile():
    do_ci = _do_ci("NODE_VERSION")

    imagem = re.search(r"^FROM node:([0-9.]+)-alpine", DOCKERFILE_FRONTEND.read_text(encoding="utf-8"), re.M)
    assert imagem, "não achei o FROM node: no frontend/Dockerfile"

    assert do_ci == imagem.group(1), (
        "a versão do Node se descolou:\n"
        f"  .github/workflows/ci.yml (env.NODE_VERSION): {do_ci}\n"
        f"  frontend/Dockerfile (FROM node:):            {imagem.group(1)}\n\n"
        "O build do frontend roda nos dois; versões diferentes significam que o "
        "bundle testado não é o bundle publicado."
    )


def test_ruff_do_pre_commit_e_o_mesmo_do_ci():
    """O hook e o CI têm de rodar a MESMA versão de ruff.

    Estavam separados por oito majors — `rev: v0.8.4` no hook contra
    `ruff==0.16.4` no CI. Duas versões de ruff são dois conjuntos de regras: o
    hook aprovava o que o CI reprovava, e o desenvolvedor descobria no PR o que
    deveria ter descoberto no commit. Ficou assim porque nada vigiava o
    `.pre-commit-config.yaml` — não havia ecossistema `pre-commit` no
    Dependabot.
    """
    do_ci = re.search(r"^ruff==(\S+)", REQ_DEV.read_text(encoding="utf-8"), re.M)
    assert do_ci, "não achei o pino do ruff em backend/requirements-dev.txt"

    texto = PRE_COMMIT.read_text(encoding="utf-8")
    do_hook = re.search(r"ruff-pre-commit\s*\n\s*rev:\s*v?(\S+)", texto)
    assert do_hook, "não achei a rev do ruff-pre-commit em .pre-commit-config.yaml"

    assert do_ci.group(1) == do_hook.group(1), (
        "a versão do ruff divergiu entre o hook e o CI:\n"
        f"  backend/requirements-dev.txt: {do_ci.group(1)}\n"
        f"  .pre-commit-config.yaml:      {do_hook.group(1)}\n\n"
        "Suba as duas juntas — versões diferentes de ruff aplicam regras "
        "diferentes, e o hook passa a discordar do CI."
    )


def test_pre_commit_nao_formata_enquanto_o_ci_nao_checa():
    """Formatação é tudo ou nada, e hoje é nada.

    O CI não roda `ruff format --check` porque o backend nunca foi formatado.
    Com um hook de formatação ativo, cada commit reformata os arquivos que
    tocar — o repositório vai sendo formatado em pedaços, dentro de commits que
    falam de outra coisa, que é o oposto do "commit isolado" que a nota do CI
    pede.

    Se um dia o `ruff format --check` entrar no CI, este teste sai junto com a
    volta do hook. Os dois na mesma mudança.
    """
    texto = PRE_COMMIT.read_text(encoding="utf-8")
    assert not re.search(r"^\s*-\s*id:\s*ruff-format\s*$", texto, re.M), (
        "`ruff-format` voltou ao .pre-commit-config.yaml, mas o CI continua sem "
        "`ruff format --check`. Ou entram os dois na mesma mudança — junto com o "
        "commit que formata o backend inteiro — ou nenhum dos dois."
    )


def test_relock_nao_tem_versao_de_python_escrita_na_mao():
    """O script tem que LER a versão, não repeti-la.

    Enquanto ele trazia `python:3.12` literal, era um quarto lugar para
    esquecer — e o mais silencioso, porque só se manifesta na próxima vez que
    alguém regenera o compilado.
    """
    texto = RELOCK.read_text(encoding="utf-8")
    codigo = "\n".join(
        linha for linha in texto.splitlines() if not linha.lstrip().startswith("#")
    )

    assert not re.search(r"python:[0-9]", codigo), (
        "scripts/relock.sh voltou a fixar a versão do Python direto no comando "
        "docker; ela deve sair do backend/Dockerfile"
    )
    assert "backend/Dockerfile" in codigo, (
        "scripts/relock.sh não lê mais a versão do backend/Dockerfile"
    )
