#!/usr/bin/env bash
#
# Regenera `backend/requirements.txt` (compilado) a partir do
# `backend/requirements.in` (fonte editada à mão).
#
# Desde que o layout virou `.in` -> `.txt`, o Dependabot regenera o compilado
# SOZINHO nos PRs dele — este script é para quando VOCÊ mexe no
# `requirements.in`. O gate "Compilado de dependências em dia" do CI reprova se
# os dois divergirem, e a mensagem dele aponta para cá, com as três coisas que
# precisam bater com o CI e que ninguém acerta de memória:
#
#   1. A MESMA versão de Python da imagem. O compilado grava a versão no
#      cabeçalho ("autogenerated by pip-compile with Python 3.14"), e compilar
#      noutra reescreve essa linha e pode mudar a resolução — o gate reprova de
#      novo, por um motivo diferente do original. Não está escrita aqui: sai do
#      `backend/Dockerfile`, e o `test_versao_de_plataforma.py` garante que os
#      lugares não se descolem.
#   2. O pip-tools da versão FIXADA em `requirements-dev.txt`. Não está
#      escrito aqui: é lido de lá, para não virar um segundo lugar onde o pino
#      mora e que ninguém lembra de atualizar junto.
#   3. In-place SOBRE o compilado versionado. Sem o arquivo de saída presente, o
#      pip-tools perde as preferências de versão e reresolve tudo para o mais
#      recente do PyPI — o diff sai gigante e sem relação com o que mudou.
#
# Roda em container para não depender do Python instalado na máquina: aqui o
# desenvolvimento é no Windows e o CI é Linux.
#
# Uso:  scripts/relock.sh [--upgrade]
#
# Sem argumento ele preserva as versões que já estão no compilado, e isso é
# deliberado (item 3 acima). O efeito colateral é que uma TRANSITIVA nunca sobe
# sozinha: o Dependabot só mexe no `requirements.in`, que lista as diretas, e a
# compilação in-place mantém o resto congelado. Em 2026-08-24 havia seis
# paradas para trás por esse motivo — `mako`, `greenlet`, `idna`, `cffi`,
# `typing-inspection` e `argon2-cffi-bindings` — sem nada no projeto capaz de
# movê-las.
#
# `--upgrade` resolve tudo de novo a partir do zero e sobe cada transitiva até
# o teto que as diretas permitem. Use quando o `pip-audit` acusar CVE em
# transitiva, ou de tempos em tempos para elas não apodrecerem. O diff é maior
# e pede a suíte rodada, por isso não é o padrão.
set -euo pipefail

MODO_UPGRADE=""
if [ "${1:-}" = "--upgrade" ]; then
    MODO_UPGRADE="--upgrade"
    echo "==> modo --upgrade: as transitivas sobem até o teto das diretas"
elif [ -n "${1:-}" ]; then
    echo "ERRO: argumento desconhecido '$1' (só existe --upgrade)" >&2
    exit 1
fi

cd "$(dirname "$0")/.."

# O `-v` do docker precisa de caminho no formato do Windows quando o shell é o
# Git Bash, e o MSYS ainda converte `/w` para `C:/Program Files/...` no meio do
# caminho se não for barrado. Mesma classe de problema que o comentário do
# `PIP_AUDIT_CMD` no Makefile descreve.
BACKEND_DIR="$PWD/backend"
case "$(uname -s)" in
    MINGW* | MSYS* | CYGWIN*)
        BACKEND_DIR="$(cd backend && pwd -W)"
        export MSYS_NO_PATHCONV=1
        ;;
esac

PIP_TOOLS_PIN="$(grep -E '^pip-tools==' backend/requirements-dev.txt)"
if [ -z "$PIP_TOOLS_PIN" ]; then
    echo "ERRO: não achei o pino do pip-tools em backend/requirements-dev.txt" >&2
    exit 1
fi
echo "==> pip-tools: $PIP_TOOLS_PIN (lido de requirements-dev.txt)"

# A versão sai do Dockerfile do backend, não de um literal aqui: o compilado
# grava o Python no cabeçalho, e se este script compilar noutra versão que a da
# imagem o gate do CI reprova. Um lugar só para subir, e o
# `test_versao_de_plataforma.py` garante que ele não se descole do resto.
PYTHON_VERSION="$(sed -n 's/^FROM python:\([0-9][0-9.]*\)-slim.*/\1/p' backend/Dockerfile | head -1)"
if [ -z "$PYTHON_VERSION" ]; then
    echo "ERRO: não consegui ler a versão do Python de backend/Dockerfile" >&2
    exit 1
fi
echo "==> Python: $PYTHON_VERSION (lido de backend/Dockerfile)"

docker run --rm -v "$BACKEND_DIR:/w" -w /w "python:$PYTHON_VERSION" sh -c "
    set -e
    python -m pip install --upgrade pip==26.2.1 -q --root-user-action=ignore
    pip install -q --root-user-action=ignore '$PIP_TOOLS_PIN'
    pip-compile $MODO_UPGRADE --output-file=requirements.txt --strip-extras --quiet requirements.in
"

echo "==> pronto. Diff:"
git --no-pager diff --stat -- backend/requirements.txt
