#!/usr/bin/env bash
#
# Regenera `backend/requirements.txt` (compilado) a partir do
# `backend/requirements.in` (fonte editada à mão).
#
# Desde que o layout virou `.in` -> `.txt`, o Dependabot regenera o compilado
# SOZINHO nos PRs dele — este script é para quando VOCÊ mexe no
# `requirements.in`. O gate "Compilado de dependências em dia" do CI reprova se
# os dois divergirem, e a mensagem dele aponta para cá, com as três coisas que
# precisam bater com o CI e que ninguém acerta de memória:
#
#   1. Python 3.12. O compilado grava a versão no cabeçalho ("autogenerated by
#      pip-compile with Python 3.12"). Compilar em 3.13 reescreve essa linha e
#      pode mudar a resolução — o gate reprova de novo, agora por um motivo
#      diferente do original.
#   2. O pip-tools da versão FIXADA em `requirements-dev.txt`. Não está
#      escrito aqui: é lido de lá, para não virar um segundo lugar onde o pino
#      mora e que ninguém lembra de atualizar junto.
#   3. In-place SOBRE o compilado versionado. Sem o arquivo de saída presente, o
#      pip-tools perde as preferências de versão e reresolve tudo para o mais
#      recente do PyPI — o diff sai gigante e sem relação com o que mudou.
#
# Roda em container para não depender do Python instalado na máquina: aqui o
# desenvolvimento é no Windows e o CI é Linux.
#
# Uso:  scripts/relock.sh
set -euo pipefail

cd "$(dirname "$0")/.."

# O `-v` do docker precisa de caminho no formato do Windows quando o shell é o
# Git Bash, e o MSYS ainda converte `/w` para `C:/Program Files/...` no meio do
# caminho se não for barrado. Mesma classe de problema que o comentário do
# `PIP_AUDIT_CMD` no Makefile descreve.
BACKEND_DIR="$PWD/backend"
case "$(uname -s)" in
    MINGW* | MSYS* | CYGWIN*)
        BACKEND_DIR="$(cd backend && pwd -W)"
        export MSYS_NO_PATHCONV=1
        ;;
esac

PIP_TOOLS_PIN="$(grep -E '^pip-tools==' backend/requirements-dev.txt)"
if [ -z "$PIP_TOOLS_PIN" ]; then
    echo "ERRO: não achei o pino do pip-tools em backend/requirements-dev.txt" >&2
    exit 1
fi
echo "==> pip-tools: $PIP_TOOLS_PIN (lido de requirements-dev.txt)"

docker run --rm -v "$BACKEND_DIR:/w" -w /w python:3.12 sh -c "
    set -e
    python -m pip install --upgrade pip -q --root-user-action=ignore
    pip install -q --root-user-action=ignore '$PIP_TOOLS_PIN'
    pip-compile --output-file=requirements.txt --strip-extras --quiet requirements.in
"

echo "==> pronto. Diff:"
git --no-pager diff --stat -- backend/requirements.txt
